name: ${name}
version: ${version}
main: ${groupId}.${name}.${name}Plugin
depend: [CivModCore]
softdepend: [NameLayer, Citadel, Bastion, CivChat2, JukeAlert, CombatTagPlus, RandomSpawn, WorldBorder]
commands:
  ep:
  suicide:
  pp:
    description: Legacy prison pearl commands
    aliases: [pplocate, ppl, ppfree, ppf, ppbroadcast, ppb, ppconfirm, ppsilence]
  