name: ${name}
version: ${version}
main: ${groupId}.${name}.${name}Plugin
depend: [CivModCore]
softdepend: [NameLayer, Citadel, Bastion, JukeAlert, CombatTagPlus, WorldBorder, MythicMobs, Brewery, BanRod]
commands:
  ep:
  suicide:
  pp:
    description: Legacy prison pearl commands
    aliases: [pplocate, ppl, ppfree, ppf, ppbroadcast, ppb, ppconfirm, ppsilence]
api-version: 1.14
